sudo: required

language: bash

services:
  - docker

before_install:
    - docker build -t vect0r/python-app .

script:
    - docker run --rm vect0r/python-app

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push vect0r/python-app;
      fi
